before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
archive:
  format: binary
  format_overrides:
    - goos: darwin
      format: tar.gz
  name_template: "footloose-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  replacements:
    386: i386
    amd64: x86_64
  files:
    - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: weaveworks
    name: homebrew-tap
  commit_author:
    name: weaveworksbot
    email: team+gitbot@weave.works
  folder: Formula
  homepage: https://github.com/weaveworks/footloose
  description: Containers that look like Virtual Machines
